// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjwksamiklznstjwjxrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqd2tzYW1pa2x6bnN0andqeHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzA3ODksImV4cCI6MjA3Mjc0Njc4OX0.GLhcL8GemuDJv-bwpP9_f-HbPa4s3sliI3ygQ_RdEf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});